name: Generate config

on:
  push:
    branches: [ master ]

env:
  FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
  FLEEK_API_SECRET: ${{ secrets.FLEEK_API_SECRET }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
        envkey_FLEEK_API_SECRET: ${{ secrets.FLEEK_API_SECRET }}
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Install
      run: yarn --immutable
    - name: Generate TokenLists
      run: yarn generate
    - name: Upload TokenLists
      uses: actions/upload-artifact@v2
      with:
        name: tokenlist-data
        path: generated/
  commit:
    needs: generate
    runs-on: ubuntu-latest
    steps:
    - name: Download TokenList
      uses: actions/download-artifact@v2
      with:
        name: tokenlist-data
        path: .
    - name: Create 'generated' branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: generated
    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: balancer-labs/assets
        ref: generated
        path: branch
        fetch-depth: 0
    - name: Commit
      id: commit
      run: |
        cd branch
        find .. -name "*.*.tokenlist.json" -exec cp '{}' generated/
        git config --global user.email "bot@balancer.finance"
        git config --global user.name "Balancer Bot"
        DIFF_LINES=$(git diff | wc -l)
        if [ $DIFF_LINES -gt 0  ]
        then
          echo "::set-output name=status::commited"
          git add .
          git commit -m "Generate config"
          git push
        fi
    - name: Make PR to master
      if: ${{ steps.commit.outputs.status }}
      uses: thomaseizinger/create-pull-request@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        head: generated
        title: "Update generated files"
        body: "Please trigger Netlify build after merging this."
